### ISSUE TITLE
Provide swap calc fn

### ISSUE THREAD

**Issue by gitmalong** [mercurial-finance/mercurial-dynamic-amm-sdk#78]
Could you provide a Rust fn that calculates the swap amount out?

**Comment by andrewsource147** [comment]
Okay, it is ready in the PR
https://github.com/mercurial-finance/mercurial-dynamic-amm-sdk/pull/79

**Comment by gitmalong** [comment]
Thank you @andrewsource147 , that's awesome. Could you also re-export the `anchor_spl` crate? I am running into version mismatches because in my app I am using another one for deserializing the `TokenAccount` type.

```rust
mismatched types
struct `anchor_spl::token::TokenAccount` and struct `anchor_spl::token::TokenAccount` have similar names, but are actually distinct types
perhaps two different versions of crate `anchor_spl` are being used?
```

**Comment by gitmalong** [comment]
Seems I could work around that by adding
```toml
anchor_spl_0_26 = { package = "anchor-spl", version = "0.26.0" }
anchor_lang_0_26 = { package = "anchor-lang", version = "0.26.0" }
```
